#----------------------------------------------------------------
# AppVeyor CI for R Packages
# https://github.com/krlmlr/r-appveyor
# Validator: https://ci.appveyor.com/tools/validate-yaml
#----------------------------------------------------------------
environment:
  _R_CHECK_FORCE_SUGGESTS_: false

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

cache:
  - C:\RLibrary -> appveyor.yml

build_script:
  - echo Current directory=%CD%
  - travis-tool.sh install_bioc DNAcopy
  - travis-tool.sh install_r aroma.core MASS matrixStats R.filesets R.methodsS3 R.oo R.utils

test_script:
  - travis-tool.sh run_tests

after_test:
  - 7z a all-Rout.zip *.Rcheck\**\*.Rout *.Rcheck\**\*.fail

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: all-Rout.zip
    name: AllRout

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
